name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change to Fitbit directory, build and run tests
        run: |
          cd fitbit
          yarn install
          yarn build
          yarn jest

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Change to Flutter directory, build and run tests
        run: |
          cd frontend
          flutter pub get
          flutter test
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk